# This file is part of the setup-specmatic.
#
# Copyright (c) 2023 airSlate, Inc.
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

version: 2

updates:
  - package-ecosystem: github-actions
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: /
    schedule:
      interval: daily
    assignees:
      - sergeyklay

  - package-ecosystem: npm
    # package.json stored in repository root.
    directory: /
    schedule:
      interval: daily
    assignees:
      - sergeyklay
    ignore:
      # v4 is ESM-only and incompatible with @vercel/ncc CJS bundling.
      # We well update to v4 when we migrate to ESM and update our bundling strategy.
      - dependency-name: "@actions/http-client"
        update-types: ["version-update:semver-major"]
